load("//tools:copts.bzl", "common_copts")

cc_binary(
    name = "handle_create_destroy_example",
    srcs = ["handle_create_destroy_example.cc"],
    copts = common_copts(),
    deps = [
        "//libs/cuaab:cuaab",
    ],
)

cc_binary(
    name = "aab_example",
    srcs = ["aab_example.cc"],
    copts = common_copts(),
    deps = [
        "//libs/cuaab:cuaab",
    ],
)