name: C++ CI with Bazel

on: [push, pull_request]

jobs:
    build:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3
          with:
           submodules: recursive

        - name: Build
          run: bazel build //...

    test:
        needs: build
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3
          with:
           submodules: recursive

        - name: Test
          run: bazel test //...

    doc:
        needs: test
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3
          with:
           submodules: recursive

        - name: Generate Doxygen documentation
          run: doxygen docs/Doxyfile

        - name: Generate Sphinx documentation
          run: sphinx-build -b html docs/source bazel-bin/docs/html

    deploy:
        needs: doc
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3
          with:
           submodules: recursive

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: bazel-bin/docs/html

