name: C++ CI with Bazel

on: [push, pull_request]

jobs:
  build_test_deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: bazel build //...

    - name: Test
      run: bazel test //...

    - name: Clean docs directory
      run: rm -rf bazel-bin/docs

    - name: Generate Doxygen documentation
      run: doxygen docs/Doxyfile

    - name: Generate Sphinx documentation
      run: sphinx-build -b html docs/source bazel-bin/docs/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: bazel-bin/docs/html
